/**
 * PDF do ADMIN / operador — painel administrativo. Rótulos usam os nomes REAIS do menu (Sites, Pontos de recarga, Conectores…).
 * Cada afirmação abaixo foi conferida no código da tela correspondente (frontend/src/pages/Admin/*) ou no próprio recorte capturado.
 */
import { DATA, DEPENDENCIAS, ETAPAS, NOTA_DEPENDENCIAS } from "./conteudo-comum.mjs"

const JANELA = "InnoFlow — Painel administrativo"

const secoes = [
  { id: "acompanhar", titulo: "Acompanhamento", subtitulo: "A operação do período e o que está acontecendo agora, numa só tela." },
  { id: "rede", titulo: "Operação da rede", subtitulo: "Locais, carregadores, conectores e o analítico de cada sessão de recarga." },
  { id: "comercial", titulo: "Comercial", subtitulo: "Quanto custa recarregar e onde cada tarifa vale." },
  { id: "financeiro", titulo: "Financeiro", subtitulo: "De onde vem cada centavo: receita, cobranças, carteiras e conciliação." },
  { id: "governanca", titulo: "Perfis e governança", subtitulo: "Quem vê o quê, quem fez o quê e como a cobrança com cartão é configurada." },
]

const slides = [
  { tipo: "capa", eyebrow: "Apresentação do sistema", titulo: "Painel <em>administrativo</em>", subtitulo: "Gestão de eletropostos, operação em tempo real e financeiro em um só lugar.", data: DATA },
  {
    tipo: "visao",
    eyebrow: "Visão geral",
    titulo: "O painel em cinco áreas",
    lead: "Do acompanhamento ao vivo à trilha de auditoria: o que o administrador e o operador usam no dia a dia.",
    areas: [
      { titulo: "Acompanhamento", texto: "Indicadores do período e sessões ao vivo.", telas: ["Dashboard", "Ao vivo"] },
      { titulo: "Operação da rede", texto: "Onde estão os carregadores e como cada sessão foi.", telas: ["Sites", "Pontos de recarga", "Conectores", "Sessões"] },
      { titulo: "Comercial", texto: "Preço por kWh, minuto e ociosidade.", telas: ["Tarifas", "Vínculos de tarifa"] },
      { titulo: "Financeiro", texto: "Receita, cobranças e carteiras dos motoristas.", telas: ["Financeiro", "Faturamento", "Movimento diário", "Pagamentos", "Carteiras"] },
      { titulo: "Perfis e governança", texto: "Acesso por papel, auditoria e pagamentos.", telas: ["ADMIN × OPERATOR", "Auditoria", "Tokens", "Gateway de pagamento"] },
    ],
    aviso: "Todas as telas deste documento foram capturadas do ambiente de demonstração, com dados fictícios. O perfil ADMIN usa 14 telas; o perfil OPERATOR, 11.",
  },

  // ------------------------------------------------------------------ 1. Acompanhamento
  {
    tipo: "tela",
    secao: "acompanhar",
    rotulo: "Dashboard",
    resumo: "Indicadores do período, comparados com o anterior",
    eyebrow: "Acompanhamento",
    titulo: "Dashboard",
    lead: "Faturamento, energia e qualidade da operação no período escolhido.",
    pontos: [
      "Seis indicadores: faturamento, sessões, energia, ticket médio, taxa de sucesso e utilização, cada um comparado com o período anterior.",
      "Filtros por período (de hoje a personalizado), por operador e por eletroposto.",
      "Gráfico de faturamento por dia e divisão entre cartão e carteira.",
    ],
    midia: { tipo: "janela", img: "adm-dashboard", titulo: JANELA },
  },
  {
    tipo: "tela",
    secao: "acompanhar",
    rotulo: "Ao vivo",
    resumo: "Sessões ativas e status dos carregadores",
    eyebrow: "Acompanhamento",
    titulo: "Ao vivo",
    lead: "O que está acontecendo nos carregadores agora, na mesma tela do dashboard.",
    pontos: [
      "Contagem de carregadores online, offline e com falha.",
      "Lista das sessões ativas: eletroposto, carregador, motorista, status, início e energia entregue.",
      "Atualização automática a cada 15 segundos.",
      "Movimento de hoje por eletroposto logo acima, com sessões, energia e faturamento.",
    ],
    midia: { tipo: "janela", img: "adm-dashboard-ao-vivo", titulo: JANELA },
  },

  // ------------------------------------------------------------------ 2. Operação da rede
  {
    tipo: "tela",
    secao: "rede",
    rotulo: "Sites",
    resumo: "Endereços onde ficam os pontos de recarga",
    eyebrow: "Operação da rede",
    titulo: "Sites",
    lead: "Os endereços físicos onde ficam os pontos de recarga.",
    pontos: ["Cadastro com nome, endereço, cidade e UF.", "Status ativo ou inativo em cada linha.", "Criar, editar e desativar direto no painel."],
    midia: { tipo: "janela", img: "adm-sites", titulo: JANELA },
  },
  {
    tipo: "tela",
    secao: "rede",
    rotulo: "Pontos de recarga",
    resumo: "Cada carregador, com comandos remotos",
    eyebrow: "Operação da rede",
    titulo: "Pontos de recarga",
    lead: "Carregadores OCPP 1.6-J: acompanhe, reinicie, destrave ou altere a disponibilidade remotamente.",
    pontos: [
      "Identidade OCPP, fabricante e modelo, site, número de conectores, tarifa e status.",
      "Comandos remotos por carregador: reiniciar (soft ou hard), destravar conector e alterar disponibilidade.",
      "Alerta quando há carregador sem tarifa: sem tarifa válida o QR não inicia a recarga.",
    ],
    midia: { tipo: "janela", img: "adm-charge-points", titulo: JANELA },
  },
  {
    tipo: "tela",
    secao: "rede",
    rotulo: "Conectores",
    resumo: "Cada tomada: tipo, potência, status e tarifa",
    eyebrow: "Operação da rede",
    titulo: "Conectores",
    lead: "Cada tomada de um ponto de recarga, com tipo, potência e status.",
    pontos: [
      "Tipo (AC Tipo 2, DC CCS2, CHAdeMO) e potência em kW.",
      "Status: disponível, carregando, com falha ou indisponível.",
      "Tarifa aplicada à tomada; “sem tarifa” aparece destacado em amarelo.",
    ],
    midia: { tipo: "janela", img: "adm-connectors", titulo: JANELA },
  },
  {
    tipo: "tela",
    secao: "rede",
    rotulo: "Sessões",
    resumo: "Analítico das recargas, com filtros e exportação",
    eyebrow: "Operação da rede",
    titulo: "Sessões",
    lead: "O analítico de todas as sessões de recarga, com filtros e detalhe.",
    pontos: [
      "Filtros por período, operador, eletroposto, status, método de pagamento e valor mínimo.",
      "Cada linha traz início, eletroposto, carregador, motorista, status, pagamento e valor.",
      "Sessões que o carregador ainda não confirmou o encerramento aparecem destacadas.",
      "Exportação em CSV.",
    ],
    midia: { tipo: "janela", img: "adm-sessoes", titulo: JANELA },
  },
  {
    tipo: "tela",
    secao: "rede",
    rotulo: "Detalhe da sessão",
    resumo: "Tudo sobre uma recarga, ao clicar na linha",
    eyebrow: "Operação da rede",
    titulo: "Detalhe da sessão",
    lead: "Um clique na linha abre o retrato completo da recarga.",
    pontos: [
      "Motorista, e-mail, carregador, conector e tarifa aplicada.",
      "Início, fim, energia entregue, ociosidade e motivo do encerramento.",
      "Composição do custo: energia, ociosidade, taxa de sessão, ajuste de cobrança mínima e total.",
      "Como a sessão foi fechada, a leitura final do medidor e os pagamentos associados.",
    ],
    midia: { tipo: "janela", img: "adm-sessoes-detalhe", titulo: JANELA },
  },

  // ------------------------------------------------------------------ 3. Comercial
  {
    tipo: "tela",
    secao: "comercial",
    rotulo: "Tarifas",
    resumo: "Preço por kWh, minuto, taxa fixa e ociosidade",
    eyebrow: "Comercial",
    titulo: "Tarifas",
    lead: "O preço cobrado do motorista: por kWh, por minuto, taxa fixa e taxa de ociosidade.",
    pontos: [
      "Modelo, preço e valor da ociosidade por minuto em cada tarifa.",
      "A coluna de vínculos mostra onde cada tarifa vale e sinaliza “sem vínculo”.",
      "Criar, editar e desativar tarifas pelo painel.",
    ],
    midia: { tipo: "janela", img: "adm-tariffs", titulo: JANELA },
  },
  {
    tipo: "tela",
    secao: "comercial",
    rotulo: "Vínculos de tarifa",
    resumo: "Onde cada tarifa vale, com vigência e prioridade",
    eyebrow: "Comercial",
    titulo: "Vínculos de tarifa",
    lead: "“Onde vale”: a tarifa pode ser ligada à operação inteira, a um local, a um carregador ou a um conector.",
    pontos: [
      "Vigência com data inicial e final (ou sem data final).",
      "Prioridade para resolver sobreposição entre vínculos.",
      "Vínculos encerrados ficam consultáveis em “Mostrar encerrados”.",
    ],
    midia: { tipo: "janela", img: "adm-tariffs-vinculos", titulo: JANELA },
  },

  // ------------------------------------------------------------------ 4. Financeiro
  {
    tipo: "tela",
    secao: "financeiro",
    rotulo: "Financeiro",
    resumo: "Resumo do período e conciliação",
    eyebrow: "Financeiro",
    titulo: "Financeiro",
    lead: "De onde vem cada centavo: faturamento, cartão, carteira e conciliação.",
    pontos: [
      "Resumo do período: faturamento, recebido em cartão, consumido de carteira, entradas via Pix, valor a receber e falhas.",
      "Conciliação: faturamento esperado, valor contabilizado e a diferença.",
      "Filtros por período e por operador.",
    ],
    midia: { tipo: "janela", img: "adm-financeiro", titulo: JANELA },
  },
  {
    tipo: "tela",
    secao: "financeiro",
    rotulo: "Faturamento",
    resumo: "Série temporal da receita, com detalhamento",
    eyebrow: "Financeiro",
    titulo: "Faturamento",
    lead: "A série temporal da receita, com detalhamento por dimensão.",
    pontos: [
      "Agrupamento por dia, semana ou mês.",
      "Detalhamento por eletroposto, carregador, método de pagamento ou tarifa.",
      "Exportação em CSV.",
    ],
    midia: { tipo: "janela", img: "adm-faturamento", titulo: JANELA },
  },
  {
    tipo: "tela",
    secao: "financeiro",
    rotulo: "Movimento diário",
    resumo: "Sessões e faturamento por dia e eletroposto",
    eyebrow: "Financeiro",
    titulo: "Movimento diário",
    lead: "Sessões, energia e faturamento por dia e por eletroposto.",
    pontos: [
      "Totais do período: sessões, energia e faturamento.",
      "Uma linha por dia e eletroposto, com sessões, energia, ticket médio e faturamento.",
      "Exportação em CSV.",
    ],
    midia: { tipo: "janela", img: "adm-movimento-diario", titulo: JANELA },
  },
  {
    tipo: "tela",
    secao: "financeiro",
    rotulo: "Pagamentos",
    resumo: "Tentativas de cobrança — cartão, Pix e carteira",
    eyebrow: "Financeiro",
    titulo: "Pagamentos",
    lead: "As tentativas de cobrança: cartão, Pix e carteira.",
    pontos: [
      "Data, usuário, eletroposto, provedor, status e valor de cada tentativa.",
      "Filtros por período, operador, provedor e status.",
      "Exportação em CSV.",
    ],
    nota: "No ambiente de demonstração os pagamentos são simulados; nenhuma cobrança real é feita.",
    midia: { tipo: "janela", img: "adm-pagamentos", titulo: JANELA },
  },
  {
    tipo: "tela",
    secao: "financeiro",
    rotulo: "Carteiras",
    resumo: "Saldo e dívida em aberto de cada motorista",
    eyebrow: "Financeiro",
    titulo: "Carteiras",
    lead: "Saldo e extrato dos motoristas da rede.",
    pontos: [
      "Busca por nome ou por e-mail exato.",
      "Saldo, dívida em aberto (destacada) e data de cadastro; indica quem está em recarga agora.",
      "Um clique abre o extrato do motorista.",
    ],
    midia: { tipo: "janela", img: "adm-carteiras", titulo: JANELA },
  },
  {
    tipo: "tela",
    secao: "financeiro",
    rotulo: "Extrato da carteira",
    resumo: "Lançamentos e ajuste de saldo auditado",
    eyebrow: "Financeiro",
    titulo: "Extrato da carteira",
    lead: "O histórico de lançamentos de um motorista, com o saldo depois de cada um.",
    pontos: [
      "Saldo atual e dívida em aberto, que bloqueia a próxima recarga.",
      "Lançamentos: recargas de veículo (débito) e recargas de saldo via Pix (crédito).",
      "“Ajustar saldo” (perfil ADMIN) e consulta ao extrato registrados na auditoria.",
    ],
    midia: { tipo: "janela", img: "adm-carteiras-extrato", titulo: JANELA },
  },

  // ------------------------------------------------------------------ 5. Perfis e governança
  {
    tipo: "perfis",
    secao: "governanca",
    rotulo: "ADMIN × OPERATOR",
    resumo: "Cada perfil enxerga só o que lhe cabe",
    eyebrow: "Perfis e governança",
    titulo: "Dois perfis, um painel",
    lead: "O operador vê apenas os dados da sua operação; as áreas da rede mostram “Acesso restrito” com o mascote.",
    esq: { titulo: "Dashboard do operador", janela: "InnoFlow — Operador", img: "op-dashboard", texto: "Mesmo painel, com os números só da própria operação e sem o filtro por operador." },
    dir: { titulo: "Tentando abrir a Auditoria", janela: "InnoFlow — Operador", img: "op-acesso-restrito", texto: "Tentar abrir a Auditoria, os Tokens ou o Gateway de pagamento mostra “Acesso restrito”." },
  },
  {
    tipo: "quadroPerfis",
    secao: "governanca",
    eyebrow: "Perfis e governança",
    titulo: "O que cada perfil usa",
    lead: "As telas do menu são ajustadas pelo papel do usuário.",
    admin: {
      titulo: "ADMIN — administrador da plataforma",
      pontos: [
        "Todas as 14 telas do painel.",
        "Visão da rede inteira, com filtro por operador e ranking de operadores no dashboard.",
        "Exclusivas: Tokens de autenticação, Auditoria e Gateway de pagamento.",
        "Ajuste de saldo das carteiras.",
      ],
    },
    operador: {
      titulo: "OPERATOR — operador de uma empresa",
      pontos: [
        "11 telas: operação, financeiro e tarifas.",
        "Dados limitados à própria operação (dashboard, relatórios e sessões).",
        "Sem Tokens, Auditoria e Gateway de pagamento: essas rotas respondem “Acesso restrito”.",
      ],
    },
    aviso: "A separação vale na tela e também no servidor: as rotas exclusivas do administrador não respondem ao operador.",
  },
  {
    tipo: "tela",
    secao: "governanca",
    rotulo: "Auditoria",
    resumo: "Quem fez o quê, quando e onde",
    eyebrow: "Perfis e governança",
    titulo: "Auditoria",
    lead: "Quem fez o quê, onde e como: a trilha de toda alteração administrativa da rede.",
    pontos: [
      "Quando, quem (nome, e-mail e papel), o quê (ação e entidade) e onde ocorreu.",
      "Filtros por período, ator, ação, resultado, entidade, operador e busca livre.",
      "Exportação em CSV. Tela exclusiva do administrador.",
    ],
    midia: { tipo: "janela", img: "adm-auditoria", titulo: JANELA },
  },
  {
    tipo: "tela",
    secao: "governanca",
    rotulo: "Tokens de autenticação",
    resumo: "RFID e tokens de app para iniciar recarga",
    eyebrow: "Perfis e governança",
    titulo: "Tokens de autenticação",
    lead: "RFID e tokens de app usados para iniciar uma recarga: identidade de rede, válida em qualquer operador.",
    pontos: ["Cadastro de identificador (idTag), tipo e status.", "Data de expiração opcional.", "Criar, alterar o status e bloquear tokens. Tela exclusiva do administrador."],
    midia: { tipo: "janela", img: "adm-auth-tokens", titulo: JANELA },
  },
  {
    tipo: "tela",
    secao: "governanca",
    rotulo: "Gateway de pagamento",
    resumo: "Conta Cielo: credenciais, ambiente e meios",
    eyebrow: "Perfis e governança",
    titulo: "Gateway de pagamento",
    lead: "A conta da operadora de pagamento (Cielo) configurada pelo painel, sem mexer em servidor.",
    pontos: [
      "Credenciais cadastradas na tela; os campos secretos são só de escrita: depois de salvos, nunca são exibidos.",
      "Ambiente de testes (sandbox) ou produção, com confirmação extra antes de ir para produção.",
      "Pix e cartão habilitados separadamente; a tela lista o que ainda falta preencher.",
      "Teste de conexão com a operadora.",
    ],
    nota: "Pagamentos funcionam hoje em modo de demonstração (sandbox/simulado); a homologação com a operadora está nas próximas etapas.",
    pendenteRecaptura: "Tela de Gateway de pagamento em redesenho: recapturar com `node apresentacao/gerar.mjs --so-capturas --quais=adm-gateway-pagamento` e gerar o PDF com `--gateway-pronto`.",
    midia: { tipo: "janela", img: "adm-gateway-pagamento", titulo: JANELA },
  },

  // ------------------------------------------------------------------ encerramento
  {
    tipo: "entregue",
    eyebrow: "Encerramento",
    titulo: "O que está entregue",
    lead: "Fatos verificáveis no ambiente de demonstração mostrado neste documento.",
    blocos: [
      {
        titulo: "Operação",
        pontos: [
          "Dashboard com indicadores do período e sessões ao vivo.",
          "Sites, pontos de recarga e conectores, com comandos remotos.",
          "Tarifas com vínculos por local, carregador ou conector e vigência.",
          "Analítico de sessões com filtros, detalhe e exportação em CSV.",
        ],
      },
      {
        titulo: "Financeiro e governança",
        pontos: [
          "Financeiro com conciliação, faturamento, movimento diário e pagamentos.",
          "Carteiras dos motoristas, com extrato e ajuste de saldo (ADMIN).",
          "Perfis ADMIN e OPERATOR, com dados separados por operador.",
          "Auditoria das ações administrativas.",
        ],
      },
      {
        titulo: "Base técnica",
        pontos: [
          "Gateway OCPP 1.6-J, API e rotinas em segundo plano construídos e testados com simulador de carregador.",
          "Pix e cartão implementados, em modo de demonstração (simulado).",
          "Testes automatizados: unidade, ponta a ponta, regressão visual e contraste de acessibilidade.",
        ],
      },
    ],
    numeros: [
      { valor: "14", rotulo: "telas do painel para o perfil ADMIN" },
      { valor: "11", rotulo: "telas para o perfil OPERATOR" },
      { valor: "5", rotulo: "relatórios com exportação em CSV" },
      { valor: "2", rotulo: "meios de pagamento: Pix e cartão" },
    ],
    aviso: "Ainda não realizado: conexão com um carregador real, homologação dos pagamentos e implantação em produção. Veja as próximas etapas.",
  },
  {
    tipo: "etapas",
    eyebrow: "Encerramento",
    titulo: "Próximas etapas",
    etapas: ETAPAS.map((e) => ({ ...e, destaque: false })),
    dependencias: DEPENDENCIAS,
    notaDependencias: NOTA_DEPENDENCIAS,
  },
]

export default {
  id: "admin",
  arquivo: "InnoFlow-Admin",
  produto: "Painel administrativo",
  titulo: "InnoFlow — Painel administrativo (apresentação)",
  descricao: "Apresentação do painel administrativo do InnoFlow. Ambiente de demonstração com dados fictícios.",
  secoes,
  slides,
}
